name: Continuous Integration
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
            go-version: '1.15.7'
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: unit tests
        run: |
          cd hello-world
          go test
      - run: echo "🍏 This job's status is ${{ job.status }}."
